### ISSUE TITLE
IMPORTANT - What we want from Koseven?

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#16]
Hello!

Now that there's some people interested. I need to launch que global question.

**Comment by neo22s** [comment]
For me there's some requirements on what I am interested.

- Koseven should be a drop in without break changes to Kohana (Unless there's a deprecated situation or security bug, like exception for PHP7 or mcrypt soon)
- We should not add new functionality unless necessary. For that we can use modules. Forking the module to add you new features or to extend them seems to me the best way.
- We need to document any minimal change that has been done. 
- We need to add tests to any change made

I have not followed this rules in this PR https://github.com/koseven/koseven/pull/1/files I can revert it or we can just document it and test it. 

I have this requirements since I have projects live that needs to be compatible with KO but they need to be updated in case theres bugs, deprecations etc... If I need to start doing heavy refactoring then I rather move to another framework. 

I do not have Koseven to grow it and make it the best FW in the market, I can not compete with Laravel symfony etc...  and honestly I do not have the time. I just want to keep running my business as lean as possible and that means no migrating the code done in the last 5 years ;) and if in this process I can help anyone struggling in the same as me.... I am more than happy to help! :D

My 5 cts.  I hope you all see it like this. If not maybe I am the wrong person for this xD I am always open to disqus and debate of course. Thats why I opened this ;)

thanks all!

**Comment by jstrobel** [comment]
I got into to contact to you, because i have same position at most of the parts and i am happy that i found more persons which have such requirements:
- Codebase on some large projects, i don't **want** and **cannot** move to another framework
- Want to work with Koseven without having to use "old" PHP because kohana isn't compatible anymore
- Stay up-to-date at the PHP

Hopeing when we are some people (which looks not bad so far), we can make this work for the next years, so nobody needs to do heavy refactoring and move to another framework for their big projects. I personally see no need for build "the best FW in the market", too. Just keep it working for a long time.

Modules are perfect i think to add new functions and keep our heads up with the documentation. But don't leave us in details, because i think we all have some work todo beside :)

**Comment by svenbw** [comment]
I like Kohana and want to support new development or maintenance (if you prefer) because:  it is quite lightweight and "_just works_".
Over the years the number of modules I used grew and I know how they work and how to use them. If I would start using a new framework for new projects I need to find a replacements (and try to guess which one is the best and most maintained) for these modules, get to know the API...

New functionality: My PR are features that I moved over time from the application to the ORM module because I needed them over and over for different projects, therefore I thought they might be useful for other people and I always try to keep the backward compatibility in mind when adding stuff to avoid breaking old code if upgrading to a new release.

Testing and documenting are a requirement. I think changes cannot be accepted without proper documentation (I tried to add these for a start in the PR).

**Comment by Hyaena** [comment]
All I have to say is already said, especially “Codebase on some large projects, i don't want and cannot move to another framework”.

**Comment by piotrgolasz** [comment]
1) Better documentation. Even the best framework is useless if the documentation is scarce and there are no code examples. I would like to contribute to solve that problem.
2) Ability to load classes via composer

**Comment by svenbw** [comment]
@piotrgolasz Documentation is (very) important but in the end I find myself always in reading the code, even in very well documented projects.

**Comment by neo22s** [comment]
@svenbw I absolutely agree ;)

@piotrgolasz code examples are great! I have released plenty, some good some bad xD see https://github.com/yclas/yclas https://github.com/neo22s/kohana-cron https://github.com/open-classifieds/open-eshop https://github.com/neo22s/adserum hope this helps :P
