### ISSUE TITLE
Kohana::cache issues

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#24]
Kohana::cache https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Core.php#L856

Always uses file text to store the cache.... even if you have set another cache....

Did you know? queries on the Database are stored using kohana::cache!! 

https://github.com/koseven/koseven/blob/master/modules/database/classes/Kohana/Database/Query.php#L242

We can not directly modify it because if you use caching for kohana internal the module of cache is not loaded yet in the init()
https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Core.php#L294

I have overwritten the function in my own kohana.php file....

```PHP
public static function cache($name, $data = NULL, $lifetime = NULL)
{
    //in case the Kohana_Cache is not yet loaded we need to use the normal cache...sucks but happens onload
    if (class_exists('Kohana_Cache'))
    {
        //deletes the cache
        if ($lifetime===0)
            return Cache::instance()->delete($name);

        //in development we do not store or read we always return null
        if (Kohana::$environment == Kohana::DEVELOPMENT)
            return NULL;

        //no data provided we read
        if ($data===NULL)
            return Cache::instance()->get($name);
        //saves data
        else
            return Cache::instance()->set($name,$data, $lifetime);
    }
    else
        return parent::cache($name, $data, $lifetime);
}
```

Suggestions? how should we handle this?

**Comment by svenbw** [comment]
We could add the cache configuration for queries in the database config. Leaving is out would mean old behavior, adding it configures it as specified.
I actually never tested if the performance of the Kohana cache is better or worse as the MySQL/MariaDB cache...

**Comment by neo22s** [comment]
I selectively choose what queries to cache and which ones not to. Since as you say the cache of the mysql can be good enough. Although if you use remote MySQL server as I do then the difference is huge on the latency specially ;)

Is super good if you use Apcu, since its really fast and to cache static stats for example.

Not sure if really need to modify the DB, since this concerns more parts of the app where you may end up using Kohana::cache() (which I love as shortcut).

**Comment by neo22s** [comment]
what do you guys think?

This is a performance improvement and does not break version API.

I believe is a mistake to be using the internal file cache if you have the kohana cache module.

**Comment by svenbw** [comment]
I would even go further; add an optional cache argument to the database config.

- If no cache is specified in the config would result in the usage of the file cache (even if the "real" cache module is available and used).
- If the cache parameter is specified and is a string: use that type of cache for db caching (default could be 'file' because it would always work, better is apc).
- If the cache parameter is specified and is a boolean:
   - `TRUE` would use the default cache type.
   - `FALSE` no cache at all.

These changes are quite small.

**Comment by neo22s** [comment]
Sounds good idea! And if nothing is set in the DB config? since the may not add this value in the config file.

For me normal behaviour would be to use the kohana cache if enabled, if not kohana cache file.

hehehe

**Comment by svenbw** [comment]
Sounds good.

**Comment by jstrobel** [comment]
Sound good for me too

**Comment by neo22s** [comment]
I have done a simpler implementation, not all the queries will be cached, only those where you specify the ->cache() method.

**Comment by L1lle** [comment]
Hi. I've just spend some time investigating this new function. I like the idea to always use the custom cache config.

But:   Kohana::init() loads the _find_file values from cache. At this time the `class_existis(Kohana_Cache)` is false, because modules have not yet been set or initialised. So Kohana loads _find_file from internal file cache, but writes the result of _find_file to a custom cache like memcache.

On my server (PHP7.2) the find_file function is extrem slow and I heavily depend on file_file to be cached. As a quick fix I had to disable the recent changes back to the original version.

Should I create a new issue for this?
