### ISSUE TITLE
Support for json config files

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#245]
At this moment all config files are PHP arrays, these arrays are difficult to update during the deployment process on the server. Typically the correct config files are copied.

If we would move from php (array based) config files to json config files the install process can be simplified.
This can be easily achieved by adding an **additional** config reader. If one switches the config reader in the bootstrap file it is possible to switch from php to json.

The structure of a combined json.config file could look like this:

```
{
    "database": {
        "default": {
            "type": "MySQLi",
            "connection": {
                ...
            }
        }
    },
    "url": {
         "trusted_hosts": [
           "localhost", "mydomain.org"
         ]
    }
}
```
It's also possible to keep the config files for the different modules separate, but the combined requires only one read.

**Comment by WinterSilence** [comment]
@svenbw - change 2 strings:
~~~
class Kohana_Config_Json_Reader implements Config_File_Reader
{
    const EXT = 'json';

    public function load($group)
    {
        $config = [];
        $files = Kohana::find_file($this->_directory, $group, self::EXT, TRUE);
        if ($files) {
            foreach ($files as $file) {
                $config = Arr::merge(
                    $config, 
                    json_decode(file_get_contents($file), TRUE)
                );
            }
        }
        return $config;
    }
}
~~~

**Comment by svenbw** [comment]
@WinterSilence thanks for the feedback and example. I have something similar (I've put config reader and json file reader into one class for testing; [see gist](https://gist.github.com/svenbw/d16cc8a60e8acfb17065b0590b06fd77).

I have no idea about the performance, my main issue was that I wanted to take a default config and patch it during the deployment on the server.

Take as an example the database; engine, prefix are equal for different servers; password, username, database differ; reading the default config, merge your own values, write it to the config directory and you're done.
If you start from a PHP array it's not that easy because you have to write your own php array writer (which is possible).
yclas uses default configs and does a search and replace, that's also an option.

Again: I not criticize the use of array's it's fits the Kohana/Koseven; It's easy to configure, understand and not bloated.
But looking at npm, composer, ... they all use json to store configurations. I assume because it's easy to modify trough software and is also quite readable. I opened this issue to see if others might benefit (see advantages or disadvantages) and if found useful add it to Koseven as a new feature that doesn't break things.

**Comment by WinterSilence** [comment]
@svenbw Difference between code of json and php configs is minimal. Config_File_Writer it`s good idea, maybe somebody write this class, I write configs in DB. I see pluses in php config - dynamic + secured, what arguments do you have?.

> But looking at npm, composer

its, not magic code for everything. changes needed only if its more useful, not more popular.

**Comment by WinterSilence** [comment]
@svenbw old version not support php>7,1, php7 work faster - its more useful, not more popular.

**Comment by donalturrentine** [comment]
It is much more useful to have environment variables (i.e. infrastructure-related configuration) defined in a file (or files) ... so you might as well have those files be a standard format that is easy to manipulate. 

I have Chef orchestrating the deployments of the app I inherited (which I just moved from Kohana to Koseven) and I intend to move away from the legacy code to a file based configuration in YAML as soon as possible.

A lot of people prefer YAML even to JSON. There are great PHP YAML resources. 

Symfony supports YAML, XML, PHP, etc simultaneously in its configuration files:

https://symfony.com/doc/current/best_practices/configuration.html

**Comment by svenbw** [comment]
I would create an additional config option (e.g. `config_syntax`) for this with the following possible values:
`TRUE`: Auto check for php, yaml or json (in that order).
`yaml`: use yaml config files (fallback to php config for backward compatibility).
`json`: use json config files (fallback to php config for backward compatibility).

This should make it possible to overload the config class with own formats based on the config string.
There will be 3 php-files included in the framework: one with the `Config_PHP` class, one with the `Config_YAML`, class and one with the `Config_JSON` class.

**Comment by neo22s** [comment]
I think what @svenbw mentions makes more sense. A config in a define in the index for example asking for what config system to use

**Comment by L1lle** [comment]
Hi, I just want to join this discussion with a smaller side note. I added the  dotenv library (vlucas/phpdoten) using composer to my Kohana 3.3.7 setup and replaced all uses of `switch(Kohana::$environment)` with e.g. `env('APP_DEBUG')`  in my config files, bootstrap.php and application.

Using JSON files for configs would make integration of .env files or ENV-params  a lot harder. But I guess it's supposed to be optional. I deploy the application on multiple environment with different .env files. But never commit any credentials or similar to my git repository.

Just my thought an this topic.

**Comment by jstrobel** [comment]
@L1lle Thanks for joining in the conversation. Yes i think as @svenbw mentioned i his solution it would be a config parameter. This would be a good option to make most people happy ;)

**Comment by WinterSilence** [comment]
@svenbw Some modules can be use json configs, some - php, app - xml. `config_syntax` doesn't work in this case.

**Comment by svenbw** [comment]
@WinterSilence It will, because if a config file is not found the fallback option is php. Since the structure is the same for the different formats they should overload.

**Comment by toitzi** [comment]
@svenbw @jstrobel
My main concern about this:
We use PHP Constants inside some of our configrations (eg. encrypt) which won't work in other config files. Guess there will be a possibility to do so and interpret those files like php...but this will be slow.

And my opinion i think adding a configuration value is not necessary, imagine:

You have Koseven Core Files (`.php` configurations):
Only setting `config_syntax` to `TRUE` will work.

You have Koseven Core Files (`.php`) and a module which uses `.json`
setting `config_syntax` to `json` will work, as it will search for `.php` if `.json` not found
setting `config_syntax` to `TRUE` will work

You have Koseven Core Files (`.php`) and a module which uses ` .yaml`
setting `config_syntax` to `yaml `will work, as it will search for `.php` if `.yaml` not found
setting `config_syntax` to `TRUE` will work

And i think most common: imagine you got multiple Modules. You will have `.json`, `.php`, `.yaml`
setting `config_syntax` to `json` will not work (`.yaml` won't get loaded)
setting `config_syntax` to `yaml `will not work (`.json` won't get loaded)
Only setting `config_syntax` to `TRUE` will work

As you can see in 2 out of 4 cases you MUST use `TRUE`, and in the other 2 cases you also can use `TRUE`

Also NOTE: Config values `YAML` and `JSON` do pretty much the same as `TRUE` except they are checking for Two files (e.g `yaml` and `php`) instead of three ... don't think it will make much of a difference to simply check for all of them.

Example:

Currently we use (very shortened) this:

`LOOP APPPATH, MODPATH, SYSPATH as PATH`

```
if (php config file is in PATH)
   -> load
```

We can simply add:
```
elseif (json config file is in PATH)
   -> load
elseif (yaml config file is in PATH)
   -> load
```

`END LOOP`

this will not slow down existing applications, because they will only use .php configuration files (which is the current state in all modules) and this check is performed anyway.

Additional `file_exists` checks will only be done if `.php` file not found (Also Note: This function 
call is also cached by PHP itself and therefore not that slow.)

**Comment by sabat24** [comment]
> At this moment all config files are PHP arrays, these arrays are difficult to update during the deployment process on the server.

You can easily save arrays using `var_export`. I keep a lot of informations in such configs instead of database and I can easily merge and overwrite default values to custom ones. You can even have got one default config file and another file with the same name in "env" dir, which is loaded depends on kohana::$environment It can be perfectly done without any changes in core files.
