### ISSUE TITLE
View supported template engines

### ISSUE THREAD

**Issue by WinterSilence** [koseven/koseven#254]
I think need add support of template engine to View.

Plus:
- more readable & shortest code
- secure: work only allowed classes/methods
- good practice for users: separate view and business logic
- engine helpers
Minus:
- speed (caching fix it)
- third-party libraries

As example https://github.com/WinterSilence/kohana-tpl
[Fenom](https://github.com/fenom-template/fenom) as default engine (not so popular, but really fast and lightweight).

**Comment by neo22s** [comment]
For me PHP it's already a template system. I know this is a recurring discussion on the PHP community. 

I think this could be done as a separated module outside the core better. ;)

**Comment by neo22s** [comment]
@WinterSilence for me a module it's much better, if they want to enable this extra functionality they can.

**Comment by WinterSilence** [comment]
@neo22s u cant overwrite `Kohana_View` twice (in module and in app) -> u cant use one type for all app templates (if u want replace views of modules/system in app). We can add only adapter interface, native adapter (php) and support for adapter in `Kohana_View` (min difference in code and execution time). Other adapters in module(s).

**Comment by WinterSilence** [comment]
@neo22s  migration is no need - if template for current adapter not found, `View` use default (native php) adapter & template.

**Comment by neo22s** [comment]
but why can we can not have this in a external module? then if someone wants to activate it then turns it on and ready ;) we do not have even the cache module which I think it's basic active by default...

**Comment by WinterSilence** [comment]
@neo22s i already try give answer: u cant extend `Kohana_View` as `View` in module because then u cant extend it in app. If u extend `View` as `Template` in module `template` then, u cant replace native php tempates of other modules in app because they use `View`.

**Comment by neo22s** [comment]
Then we can use different syntax or naming. No need to use view.

I just do not see the advantage of having this in Koseven core.

We can vote for 3 options, I think it's the most fair in this cases since I am 100% biased do to the nature of my project and I am not objective I believe.

1- Do nothing
2- Integrated in the core with a backwards compatibility
3- as a module

**Comment by WinterSilence** [comment]
@neo22s Ok, example: app template `app/views/profiler/stats.twig`(twig adapter), default template: `system/views/profiler/stats.php` (native php adapter). How display stats.twig and extend `Kohana_View` as `View` in app (i want add special method for this app) + extend `Kohana_View` as `View` in module `template` (support for adapters)? I cant extend `Kohana_View` as `View` twice: if extend `View`  as `Template` in module then need extend `Profiler` in app (replace  `View` to `Template`).

**Comment by WinterSilence** [comment]
@neo22s i show why add it in module - bad idea.

**Comment by Sebjugate** [comment]
I vote module. 

Make a new class, Twig_View or Template_View or something. People will just have to be explicit when they want to use it, which is a good thing in my opinion. Views are currently very light in Kohana, and don't need additional complications with adapters and whatnot.

As for your example, wherever you want to display profiler/stats.twig you'd simply do something like Twig_View::factory('profiler/stats') instead of View::factory('profiler/stats'). No need to extend Profiler or View.

**Comment by WinterSilence** [comment]
@Sebjugate `profiler/stats` - bad example (no methods with `View::factory('profiler/stats')`), let's take `koseven/modules/pagination/views/pagination/basic.php` or ` koseven/system/views/kohana/error.php`.

**Comment by toitzi** [comment]
I tend to agree to @neo22s and @Sebjugate,
i think "keeping" it as module would do just fine.

**Comment by toitzi** [comment]
Idle (except my comment) for nearly 2 months. Voting was: 3 Module, 1: System.
Closing this issue. If someone wants to vote again, make some input, etc,...feel free to reopen.
