### ISSUE TITLE
ORM::changed() specification does not match implementation

### ISSUE THREAD

**Issue by Sebjugate** [koseven/koseven#300]
https://github.com/koseven/koseven/blob/5c0a70a0914fac777fa6757f7ca9b107a44d9ab1/modules/orm/classes/Kohana/ORM.php#L583-L594

PHPDoc states that ORM::changed() should return a bool. However, it returns a string or NULL.

Given column 'foo' and a call $model->changed('foo'):

 Is Changed? | PHPDoc | Actual Result
--------------|----------------|------------
 Yes |  TRUE | 'foo'
 No | FALSE | NULL

Is the documentation wrong, or is the implementation wrong? I would be happy to submit a fix, but need to know how to fix it :)

I would lean toward changing the documentation since that is less likely to break existing code. However, I like the idea of a boolean return better.

**Comment by toitzi** [comment]
That's probably a mistake yes, but maybe we should fix docs and implement another function like `has_changed` or smth. which returns true or false, because if someone currently uses this for example to check what was `$field` changed to, we will break his application, but since this was documented to return true or false i am not really sure....what do others say?

**Comment by neo22s** [comment]
Like your approach. Change docs to what actually does and create a new
method has changed.

**Comment by jstrobel** [comment]
Agree to Tobias. Fix the docs and another function.

**Comment by Sebjugate** [comment]
Ok, I will try to submit a patch in the New Year. Merry Christmas & Happy New Year everyone :)
