### ISSUE TITLE
Image module - WebP support

### ISSUE THREAD

**Issue by roman-huliak** [koseven/koseven#32]
Hi,
can someone improve Image module and add webp support for images manipulation?
Support in PHP7 for webp si very good.

**Comment by neo22s** [comment]
can you help in this?

**Comment by svenbw** [comment]
There are only a [hand full of browsers](https://developers.google.com/speed/webp/faq#which_web_browsers_natively_support_webp) that support webp.
It gets even better, image_type_to_mime_type doesn't know the format either.

I have the code (almost) ready, but not fully tested. But should we include it since the limited browser support?

**Comment by neo22s** [comment]
I will add it, later is optional for whom is implementing it to accept it or not ;)

**Comment by svenbw** [comment]
Okay. I hope to finish the Imagick support this evening
