### ISSUE TITLE
webp support not working because typo in source

### ISSUE THREAD

**Issue by Daijobou** [koseven/koseven#326]
Here https://github.com/koseven/koseven/blob/master/modules/image/classes/Kohana/Image/GD.php#L105

`case self::IMAGETYPE_WEBP:`

That "self::" is wrong. After remove this part, its working fine.

Same with Imagick
https://github.com/koseven/koseven/blob/master/modules/image/classes/Kohana/Image/Imagick.php#L324

`$type = SELF::IMAGETYPE_WEBP;`

**Comment by toitzi** [comment]
Thanks for noticing this, i will patch this and notify you here as soon as the patch is merged.
Thanks a lot! :)

**Comment by toitzi** [comment]
Not sure why this is not working but code seems to be correct.
`IMAGETYPE_WEBP` is defined in `Kohana_Image` [here](https://github.com/koseven/koseven/blob/37cbbb88b240250689ebe56929a3fb5971409db9/modules/image/classes/Kohana/Image.php#L26), because PHP at this time did not support WEBP.  Therefore `self::IMAGETYPE_WEBP` should be correct, if you got an errror using this, please write doen what exactly you did and what was the error that occurred. Althrough it now supports WEBP we shall still update this.

**Comment by Daijobou** [comment]
I get message from https://github.com/koseven/koseven/blob/master/modules/image/classes/Kohana/Image/GD.php#L112
> Installed GD does not support webp images

So $create was not set. After change
`case self::IMAGETYPE_WEBP:`
to
`case IMAGETYPE_WEBP:`
its working fine. More I can't say.

**Comment by toitzi** [comment]
> **IMAGETYPE_WEBP** exists in PHP constants since PHP 7.1.0

We will merge this in devel branch than and it will be released with 4.0, thanks a lot for identifying and reporting this issue to us, we really appreciate that! 🙂

**Comment by ws17** [comment]
For those who did not work, the DG version should be at least version 2.2.4, and the webp support function should be enabled, ask the hosting about it.

and also make an edit to /modules/image/classes/Kohana/Image/GD.php

case self::IMAGETYPE_WEBP:
$create = 'imagecreatefromwebp';
break;

delete self::
case IMAGETYPE_WEBP:
