### ISSUE TITLE
Client IP in public/index.php instead Request.php

### ISSUE THREAD

**Issue by Daijobou** [koseven/koseven#341]
I found this topic https://github.com/koseven/koseven/issues/111 so I remember a important change of my code many years ago in kohana 2.x/3.x. I don't like it, that I must load the whole framework before I have the correct IP, because I need the IP long before I loading the framework.

When I make updates or converting things I must lock the access except for my IP, so I can working with it. Other very importing thing is, that with php errors I send me a e-mail with that error data and IP. So I can fix this error asap and see it was a visitor or bot/crawler that found this error. Another case is check for banned ips or ban ips that create a defined error (hacker/cralwer trap). This things should/**must** happen before loading kohana, because its make no sense in many ways and often not working after loading kohana. When something in kohana break, I will never get a e-mail with error datas or I must loading the whole framework for a attacker only to cancel his access, thats costs only needless performance.

Actual I had a copy of this Request::$client_ip stuff in Request.php and dropped it in index.php at top. So I have the correct IP from beginning. So I update in index.php $_SERVER['REMOTE_ADDR'] and use only this variable.

That feature not break anything, its only move line 102 -133 to index.php and set
`$_SERVER['REMOTE_ADDR'] =` instead `Request::$client_ip = ` in this lines.
In Request.php https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Request.php#L137 only this line is needed.

I hope it was understood a little what I mean :)

I move and edit lines from Request.php to index.php
```
$trusted_proxies = array('127.0.0.1', 'localhost', 'localhost.localdomain', 'my_server_ipv4', 'my_server_ipv6');
if (isset($_SERVER['HTTP_CF_CONNECTING_IP']) AND isset($_SERVER['REMOTE_ADDR']) AND in_array($_SERVER['REMOTE_ADDR'], $trusted_proxies))
{
	// If using CloudFlare, client IP address is sent with this header
	$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];
}
elseif (isset($_SERVER['HTTP_X_FORWARDED_FOR']) AND isset($_SERVER['REMOTE_ADDR']) AND in_array($_SERVER['REMOTE_ADDR'], $trusted_proxies))
{
	// Use the forwarded IP address, typically set when the client is using a proxy server.
	// Format: "X-Forwarded-For: client1, proxy1, proxy2"
	$client_ips = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
	$_SERVER['REMOTE_ADDR'] = array_shift($client_ips);
	unset($client_ips);
}
elseif (isset($_SERVER['HTTP_CLIENT_IP']) AND isset($_SERVER['REMOTE_ADDR']) AND in_array($_SERVER['REMOTE_ADDR'], $trusted_proxies))
{
	// Use the forwarded IP address, typically set when the client is using a proxy server.
	$client_ips = explode(',', $_SERVER['HTTP_CLIENT_IP']);
	$_SERVER['REMOTE_ADDR'] = trim(end($client_ips));
	unset($client_ips);
}
```
After
`// -- Configuration and initialization` I set:
```
Request::$trusted_proxies = $trusted_proxies;
unset($trusted_proxies);
```
And remove lines 102 - 133 in Request.php and change elseif to if for
```
			if (isset($_SERVER['REMOTE_ADDR']))
			{
				// The remote IP address
				Request::$client_ip = $_SERVER['REMOTE_ADDR'];
			}
```

**Comment by toitzi** [comment]
Hey @Daijobou,
first of all thanks a lot for your detailed description. Here are some of my thoughts:

> When I make updates or converting things I must lock the access except for my IP, so I can working with it. 

IP-Restriction should not be done via the `index.php` or PHP in general. This should be done via the webserver configuration. [Here](https://serverfault.com/questions/776252/allow-access-to-apache-server-from-only-one-ip-address/776256) is a little example for doing this via Apache.

> Another case is check for banned ips

That's something that should definitley happen on Server level and not on Framework level. If you want to ban Ip's for stuff like: country/region, brutforcing, wrong logins, ddos, etc.. i recommend a tiny software called `fail2ban` which does this job very great. (Basicly you can ban ips for any kind of stuff those above just were some examples)

With my tipps/recommendations above you will definitly get better performance and security.

> Other very importing thing is, that with php errors I send me a e-mail with that error data and IP

You can simply extend/modify the `Log` class and send an E-Mail if an error occurs / is beeing logged. Of course this is done within the framework initilization, but since errors only should happen inside initialization (`index.php` should not be modified so much, errors pretty much cannot happen there), this won't take much time / cost much performance.

Those above are some of my recommendations and primary the reason i do not think it is neccessary to implement your feature into the Koseven core application. Althrough if you say you absolutley need this feature feel free to modify the code to your needs. This is only my opinion, maybe i am biased, so this is not a decline for your feature request.

Hope i could help you a bit.

**Comment by Daijobou** [comment]
Thanks for your good answer. :)

You are right with access restriction per apache/nginx config. Only in mind, not anyone have access to server config or webhosting htaccess is not allowed. For me its simple the easiest way and its very rare.

fail2ban is a good tool but not anyone have it or newest version 1.x that support ipv6 and you must set fail2ban ban in person, you have no access per php. For a banned client-ip the ressources should be reduced to a minimum. I have a simple system that create a md5(client-ip)-file and must only check per file_exists to throw http status 403. A way to add client-ip per php to fail2ban would be much better solution.

I have included a own execption handler in index.php and its working fine. I don't need this feature, I already have it since kohana 2.x. Its was only a recommandation, because I think the client-ip should be ready before kohana initialization for some reason. When you think that make no sense, I close this ticket. Thanks for reading and responses. :)
