### ISSUE TITLE
ErrorException [ Fatal Error ]: Class Kohana_Database_MySQLi_Result contains 1 abstract method

### ISSUE THREAD

**Issue by sabat24** [koseven/koseven#371]
I got a strange problem at the time the server was under a bit heavy traffic. I have never seen such error before and I have no idea why it points out to SeekableIterator interface. I've checked my files and all methods are implemented. That error appeared twice and then disappeared. 

I attached full error log, maybe you have got idea what was happened.
[db_error.log](https://github.com/koseven/koseven/files/3428781/db_error.log)

It is a plain html file, but I had to change extension to upload it here.

**Comment by toitzi** [comment]
Very interesting what i have found after some google search:

[here](https://stackoverflow.com/questions/34586480/abstract-method-in-php-7-0-1) and
[here](https://community.woltlab.com/thread/245626-doppelte-posts-seit-php-7/) - Warning German

seems like some people had this kind of Problem with `SeekableIterator` in PHP 7.0.1
is this you PHP Version? They say it got fixed for them after they upgraded to 7.02.

If that is not the case it's kinda hard for me to find the issue because it does not quite look like a issue in the Database class, but i will try to investigate further if the above does not apply to you.

**Comment by sabat24** [comment]
Thanks for information. It seems that there is problem with PHP compilation under Windows only. I use 7.0.23 so there have to still something wrong. I think it's not worth your time as it is not so common, seems that is not related to Kohana and mostly under Windows, which is mainly a development system - not the production one.
