### ISSUE TITLE
router seem to decode %2F (in /) although it should not

### ISSUE THREAD

**Issue by gagarine** [koseven/koseven#382]
I have URL that are in the form of `page/validate/<code>` .

The code is a argument that is encrypted using `Encrypt::instance()->encode()`. Therefor this argument can contain %2F like in the url `page/validate/%2FHpHx8jejgrw6Zbt3eWP9AFd` . In that case the router interpret the url as `page/validate//HpHx8jejgrw6Zbt3eWP9AFd` and send me a 404 back

**Comment by toitzi** [comment]
@gagarine 

To me this is expected behavior.... "%2F" get's converted to "/" by the function "rawurldecode"...in my eyes that's how it should work, because otherwise we would not support encoded urls.

You are not passing the string as GET Parameter, you are passing it as Route Parameter, therefore it gets treated like one.

What you should do? Pass it either as "GET" Variable or encode it as "base64" and send it that way.

So no bug of koseven in my eyes...but

@jstrobel @neo22s What do you think?

**Comment by gagarine** [comment]
Apparently Laravel works the same way.

But in Laravel you can use an encoded / if it's the last parameters. See
https://github.com/laravel/framework/issues/22125

So not a big, but it can perhaps be improved for the last parameters. The
doc should perhaps mention that encoded slash are treated as slash.

**Comment by jstrobel** [comment]
Never had this :)
To me it is excepected like @toitzi said. Don't know so far there is a parameter for Apache:
`AllowEncodedSlashes`
which you can modify the behaivor of the Apache for that.
I don't think we should change the behaviour because my consern is, that we get bugreports in the opposite way (i use %2F and i don't work like i excepected). For me it would be a module in my project which changes the behaviour.

But i am open for discussion ;)

**Comment by toitzi** [comment]
@jstrobel 

> Don't know so far there is a parameter for Apache:
AllowEncodedSlashes

Yes you have to enable that anyway...otherwise you will get a 404 by apache, cause the redirection want work

> get bugreports in the opposite way

That's also my concern

> But i am open for discussion ;)

Me too :)

@gagarine But as mentioned before i would suppose you do not do it that way.

Even if it would work, the design itself would have flaws....you "encrypted" stuff get's cached and logged, search engines will have problems, etc.....

If you need to pass a crypto value you should use `POST` and send it in the body with e.g `x-www-form-urlencoded` ....that way you don't cache the encrypted stuff, and you don't have problems with search engines, etc....

If `POST` is not an option and you do not care about secret being logged / cached you can then send it via `GET` as a parameter.... e.g.:
`https://www.example.com/page/validate?secret=yoursecrethashwhateveritcontains%2F`

**Comment by gagarine** [comment]
I agree with you, we should not change the behavior.

This is not my implementation, it's an old (and pretty buggy) system that I have now to update and maintain. It's actually pretty fun to work on that :).

Yeah, the secret can be cached (and should!). Actually secret should not have been used at the first place has it's not really "secret" (the same secret is shared to all users) . They should have used an hash and simply save this hash in the database.

For the moment, I'm going to run the encode function until it return an secret without %2F and will change it to hash ASAP.

Thanks!

**Comment by AsafMazuz1** [comment]
Hey,
Facing this problem with moving old website to laravel.
I solved it by making an extra route with:
Origin Route:
  Route::get('/{query}', [\App\Http\Controllers\Front\User\CategoryController::class, 'category'])->name('category');
Extra Route on the end of the route file:   
 Route::get('/{query}/{more?}', [\App\Http\Controllers\Front\User\CategoryController::class, 'category'])->name('category');

And now everything works fine :)
