### ISSUE TITLE
Insulation system files

### ISSUE THREAD

**Issue by knbv** [koseven/koseven#69]
I propose to move the files index.php, install.php, example.htaccess in a separate folder, (public), it will isolate other system files ( .gitignore, composer.json, .travis.yml, etc) that should not be accessible from the outside.

Also, it will allow you to manage public files more efficiently

What do you think of it?

**Comment by neo22s** [comment]
agree... first I thought is more convenient since someone could download the zip file upload to the hosting and make it work... but does not make sense.

I propose also to add a vhost config sample for apache and nginx

I was thinking to remove from all the files ```<?php defined('SYSPATH') OR die('No direct script access.');``` since only slows down, but for projects like https://github.com/yclas/yclas that are "installable" we can not have the public folder somewhere else... :(

We need to review all paths references to index.php should be easy.

I like this change! @knbv do you want to do a PR? and we have this for 3.3.7 release? I don't think breaks anyone code.... at least not mine. :P

**Comment by jstrobel** [comment]
@knbv sound good to me too, nice request. Shouldn't break something in my enviroment too.

**Comment by knbv** [comment]
> I was thinking to remove from all the files <?php defined('SYSPATH') OR die('No direct script access.'); since only slows down, but for projects like https://github.com/yclas/yclas that are "installable" we can not have the public folder somewhere else... :(
That is, we should not delete these lines?

I think that certain specific projects should independently provide security, for example, you can use .htaccess
If this increases the speed of the system as a whole, then why not?

**Comment by neo22s** [comment]
@knbv back on PHP 5 I remember the function defined was one of the slowest ones.

Adding just security by htaccess wont be enough but I get your point.

**Comment by knbv** [comment]
Ok, I'll prepare a PR ;)
